import "./globals.css";
import type { Metadata } from "next";
import { Locale, i18n } from "@/i18n.config";
import Header from "./components/header";
import NextBreadcrumb from "./components/nextBreadcrumb";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript"],
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  authors: [{ name: "Seb" }, { name: "Josh", url: "https://nextjs.org" }],
  creator: "Jiachi Liu",
  publisher: "Sebastian Markbåge",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("http://localhost:3001"),
  alternates: {
    canonical: "/",
    languages: {
      zh: "/zh",
      de: "/de",
      en: "/en",
    },
  },
  openGraph: {
    images: "/og-image.png",
  },
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={`${inter.className} container px-16`}>
        <Header lang={params.lang} />
        <NextBreadcrumb
          separator={<span> {">"} </span>}
          activeClasses="text-amber-700"
          containerClasses="flex py-2 bg-amber-100 w-max text-xs"
          listClasses="hover:underline mx-2 font-bold"
          capitalizeLinks
          lang={params.lang}
        />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
